/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z9tYT2os8Qr
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

export default function cpfCardComponent() {
  return (
    <main className="w-full h-[calc(100vh-10vh)]">
      <div className="mt-8 w-full h-full max-w-[800px] container mx-auto display-flex flex-col justify-center items-center">
        <h1 className="text-center text-4xl font-bold font-roboto">
          Por que pedimos este dado?
        </h1>
        <ol className="mt-8 gap-[15px] text-center text-xl font-roboto">
          <li>
            <p className="pt-4">
              - Utilizamos o CPF para validar se uma pessoa já votou ou não em
              nossas pesquisas, visando uma pesquisa justa e verdadeira.
            </p>
          </li>
          <li>
            <p className="pt-4">
              - Protegemos os dados utilizados dos nossos usuários, garantindo a privacidade e segurança dos dados.
            </p>
          </li>
          <li>
            <p className="pt-4">
              - Utilizamos o CPF para validar se uma pessoa já votou ou não em
              nossas pesquisas, visando uma pesquisa justa e verdadeira.
            </p>
          </li>
        </ol>
        <p className="mt-[100px] mx-auto text-center text-xl font-bold font-roboto">
          Não armazenamos NENHUM dado pessoal com outras finalidades.
        </p>
      </div>
    </main>
  );
}
