# services:

#   postgresql:
#     env_file:
#       - path: ./.env
#     image: bitnami/postgresql:latest
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     volumes:
#       - ./pgdata:/data/postgres

# volumes:
#   postgresql_data:

services:
  cockroachdb:
    image: cockroachdb/cockroach:v22.2.0
    command: start-single-node --insecure
    ports:
      - 26257:26257
      - 8080:8080
    environment:
      - COCKROACH_USER=${POSTGRES_USER}
      - COCKROACH_PASSWORD=${POSTGRES_PASSWORD}
      - COCKROACH_DB=${POSTGRES_DB}
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach_data: